#!/usr/bin/env bash
# advanced task, multiple rolled into one
echo $$ > "/var/run/holbertonscript.pid"
trap "echo 'I am invincible!!!'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm '/var/run/holbertonscript.pid'; kill -s KILL '$(pgrep -f 7-highlander)'" SISQUIT
trap "rm '/var/run/holbertonscript.pid'; kill -s KILL '$(pgrep -f 7-highlander)'" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done