#!/usr/bin/env bash
# advanced task, multiple rolled into one
echo $$ > "/var/run/holbertonscript.pid"
trap "echo 'Y U no love me?!'" SIGINT
trap "rm '/var/run/holbertonscript.pid'; kill -s KILL '$$'" SIGQUIT
trap "rm '/var/run/holbertonscript.pid'; echo 'I hate the kill command'; kill -s KILL '$$'" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
