#!/usr/bin/env bash
# test the holbertonfile
if [ -e "holbertonschool" ] then
   if [ ! -s "holbertonschool" ] then
      echo "holbertonschool file is empty"
   else
      echo "holbertonschool file is not empty"
   fi
   if [ -f "holbertonschool ] file then
      echo "holbertonschool is a regular file"
   fi
else
   echo "holbertonschool file does not exist"
fi