#!/usr/bin/env bash
# test the holbertonfile
if [ -a "holbertonschool" ]
then
    if [ ! -s "holbertonschool" ]
    then
	echo "file is empty"
    else
	echo "file is not empty"
    fi
    if [ -f "holbertonschool" ]
    then
      echo "is a regular file"
    fi
else
   echo "file does not exist"
fi
