#!/usr/bin/env bash
# setup nginx server with html file + 404 & header
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c "echo Ceci n\'est pas une page > /var/www/html/error404.html"
target="^\tlocation / {"
replace="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By $HOSTNAME;\n\n\tlocation / {"
sudo sed -i "s@$target@$replace@" /etc/nginx/sites-available/default
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtu.be/A311CnTjfos;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$target@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart
