#!/usr/bin/env bash
# Installing HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

sudo sh -c echo "
frontend http_web
\tbind *:80
\tstats uri /haproxy?stats
\tdefault_backend custom_backend
backend custom_backend
\tbalance roundrobin
\tserver web-01 34.73.219.167:80 check
\tserver web-02 35.243.146.150:80 check" >> /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
