#!/usr/bin/env bash
# Installing HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

str="frontend http_web
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend custom_backend
\nbackend custom_backend
\n\tbalance roundrobin
\n\tserver web-01 34.73.219.167:80 check
\n\tserver web-02 35.243.146.150:80 check"
echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
